### ISSUE TITLE
Power LED blinks and button is unresponsive

### ISSUE THREAD

**Issue by npburns224** [Sinclair81/Homebridge-Tasmota-TS#1]
I am able to connect and control my smart outlet from Homebridge, but the power button on the device doesn't do anything when pressed. Also, the power LED blinks constantly regardless of whether the relay is on or off. 
This is the model I'm using: https://templates.blakadder.com/acashna_hs108.html

**Comment by Sinclair81** [comment]
That sounds like a problem with the Tasmota firmware. Check again whether all settings of the socket are correct! The blinking LED may be due to the fact that MQTT is activated but not used, deactivate it if you do not want to use it.
I will close the issue. But if you send me an email with the information(http://ip-address-plug/in) and the configuration(http://ip-address-plug/tp) of the socket and the configuration of the homebridge, I will be happy to help you.
